server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.191.128
gmall:
  jwt:
    pubKeyPath: D:\workspace_idea0722\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key
