server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://192.168.191.128:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.191.128
    port: 5673 #在虚拟机上我的5672端口被占用
    username: zzy #rabbitmq的登录名字
    password: zzy910307
    virtual-host: /zzy
